# Generated by Django 3.2.8 on 2021-12-17 00:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='default', max_length=256)),
                ('account', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('is_vaild', models.BooleanField(default=True, verbose_name='账号有效')),
                ('has_confirmed', models.BooleanField(default=False, verbose_name='已进行邮箱验证')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('male', 'man'), ('female', 'woman'), ('unknown', 'unknown')], default='unknown', max_length=32)),
                ('birthday', models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.CharField(blank=True, default='说点啥吧。', max_length=256)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.myuser')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'ordering': ['-c_time'],
            },
        ),
    ]
