# Generated by Django 3.2.8 on 2021-12-17 00:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superaccount', models.CharField(default='default', max_length=256)),
                ('mynickname', models.CharField(default='default', max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=256)),
                ('superuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.myuser')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='todoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listname', models.CharField(default='default', max_length=256, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todouser')),
            ],
            options={
                'verbose_name': '分组',
                'verbose_name_plural': '分组',
            },
        ),
        migrations.CreateModel(
            name='todoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('p_time', models.DateTimeField(default=datetime.datetime(2021, 12, 18, 0, 9, 39, 821833))),
                ('f_time', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('status', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=256)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todolist')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
            },
        ),
    ]
